### ISSUE TITLE
Relicense to Apache 2.0

### ISSUE THREAD

**Issue by nikhiljha** [ocf/transpire#7]
Can we get approval from everyone to relicense this to Apache 2.0?

If you've been mentioned, please comment with "I agree" if you agree to the following statement:

> I agree to license all my past and future contributions to this code repository under the Apache 2.0 license.

@nelson-lojo @oliver-ni @ethanwu10 @nikhiljha @tnthi115

This issue will be closed once everyone agrees.

**Comment by nikhiljha** [comment]
I agree

**Comment by tnthi115** [comment]
I agree

**Comment by oliver-ni** [comment]
I agree

**Comment by nelson-lojo** [comment]
I agree

**Comment by ethanwu10** [comment]
I agree
